# Generated by Django 3.1.5 on 2021-01-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210107_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products', verbose_name='Продукт'),
        ),
    ]
