# Generated by Django 3.1.5 on 2021-01-07 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sale_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='salerman',
        ),
        migrations.AlterField(
            model_name='sale',
            name='salesumm',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Сумма товара, руб.'),
        ),
        migrations.CreateModel(
            name='SaleCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salecheckcode', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Код чека')),
                ('salechecksumm', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Сумма чека, руб.')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sale', verbose_name='Продажа')),
                ('salerman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salerman', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
