# Generated by Django 3.1.5 on 2021-01-07 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210107_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Цена, руб.'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productgroup', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='salecheck',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sale', verbose_name='Продажа'),
        ),
        migrations.AlterField(
            model_name='salecheck',
            name='salerman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salerman', verbose_name='Продавец'),
        ),
    ]
