# Generated by Django 3.1.5 on 2021-01-08 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210107_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=80, unique=True, verbose_name='Название фирмы')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг(1-10)')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='productGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productgroup', verbose_name='Отдел продуктов'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='Фирм'),
        ),
    ]
