# Generated by Django 3.1.5 on 2021-01-09 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210109_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotioncode', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Код акции')),
                ('promotionname', models.CharField(max_length=250, verbose_name='Название акции')),
                ('description', models.TextField(blank=True, verbose_name='Описание акции')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.AlterModelOptions(
            name='salerman',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='salerman',
            name='salercode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Код работника'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverycode', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Код доставки')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.promotion', verbose_name='Акция')),
                ('saleCheck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salecheck', verbose_name='Чек')),
                ('salerman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salerman', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
